/* MIDI CCs and parameter numbers*/
#define CC_BANK_SELECT 0
#define CC_MOD_WHEEL 1
#define CC_BREATH_CONTROLLER 2
#define CC_FOOT_SWITCH 4
#define CC_VOLUME 7
#define CC_PAN 10
#define CC_BANK_SELECT_LSB 32
#define CC_SUSTAIN 64
#define CC_FILTER_RESO 103
#define CC_FILTER_FREQUENCY 104
#define CC_FILTER_ENV_MOD 105
#define CC_DELAY_TIME 106
#define CC_DELAY_FEEDBACK 107
#define CC_DELAY_VOLUME 108
#define CC_DELAY_FILTER_FREQUENCY 109
#define CC_DELAY_FILTER_RESO 110
#define CC_PANIC 120
#define CC_RESET_CONTROLLERS 121
#define CC_NOTES_OFF 123
#define CC_SET_MONO_MODE 126
#define CC_SET_POLY_MODE 127

/* Helpers */
#define DRY_SIGNAL 0
#define WET_SIGNAL 1
